// src/app/api/posts/[id]/route.ts
import { NextResponse } from "next/server";
import { createClient } from "@/lib/supabase/server";

export async function PUT(
  req: Request,
  { params }: { params: { id: string } }
) {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id } = params;
  const { title, slug, content, excerpt, cover_image, status } = await req.json();

  if (!title || !slug || !content) {
    return NextResponse.json({ error: "Missing required fields" }, { status: 400 });
  }

  // Check if the slug is unique (excluding the current post)
  const { data: existingPost, error: slugCheckError } = await supabase
    .from("posts")
    .select("id")
    .eq("slug", slug)
    .neq("id", id)
    .single();

  if (slugCheckError && slugCheckError.code !== 'PGRST116') {
    return NextResponse.json({ error: "Database error while checking slug." }, { status: 500 });
  }

  if (existingPost) {
    return NextResponse.json({ error: "This slug is already in use by another post." }, { status: 409 });
  }

  const postData = {
    title,
    slug,
    content, // Markdown content
    html: null, // HTML is no longer generated by the editor
    excerpt,
    cover_image,
    status,
    published_at: status === "published" ? new Date().toISOString() : null,
    updated_at: new Date().toISOString(),
  };

  const { data, error } = await supabase
    .from("posts")
    .update(postData)
    .eq("id", id)
    .select()
    .single();

  if (error) {
    console.error("Error updating post:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json(data, { status: 200 });
}

export async function DELETE(
  req: Request,
  { params }: { params: { id: string } }
) {
  const supabase = createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { id } = params;
  const { error } = await supabase.from("posts").delete().eq("id", id);

  if (error) {
    console.error("Error deleting post:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return new Response(null, { status: 204 }); // Return 204 No Content on successful deletion
}
